#!/usr/bin/env ruby
# Sets up an environment where ActiveRecord classes are allowed to run free of the database
# Expectations: you will not have persistance except through manual efforts

# find irb appropriately
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

# set up class loading path for files called immediately by this script
$: << File.dirname( __FILE__) + '/../lib'

# create an irb process requiring and setting up load path for it per DbFreeIncludes
require 'db_free_includes'
libs = DbFreeIncludes::IRB_REQUIRES.inject(""){ |all, this| all << "-r #{this} "}

load_path = DbFreeIncludes::IRB_LOAD_PATHS.inject("") do |all, this|
  all << " -I " + File.expand_path( File.join( File.dirname( __FILE__), "/../#{this}" ) )
end

cmd_line = "#{irb} #{load_path} #{libs} --simple-prompt"
puts cmd_line
exec cmd_line

